In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [68]:
import warnings
warnings.filterwarnings('ignore')

In [69]:
from sklearn.datasets import make_classification

In [4]:
X,y=make_classification(n_samples=1000,n_features=5,n_clusters_per_class=1,n_classes=2,random_state=2529)

In [5]:
X[0:5]

array([[ 1.54701705,  0.84770596, -0.41725021, -0.62356778, -0.19388577],
       [ 0.80633556,  0.40985594, -0.45641095, -0.3052022 ,  0.50935923],
       [ 0.94390268,  0.70041038,  1.11385452, -0.49394417,  1.42305455],
       [ 1.92091517,  0.95815739, -1.2235022 , -0.71578154,  0.66588981],
       [ 1.45270369,  0.69035375, -1.18119669, -0.52009219, -0.22745417]])

In [6]:
y[0:5]

array([0, 0, 1, 0, 0])

In [7]:
X.shape,y.shape

((1000, 5), (1000,))

In [8]:
#get train test split

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=2529)

In [11]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((700, 5), (300, 5), (700,), (300,))

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
model=DecisionTreeClassifier()

In [14]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [15]:
#get model predictions

In [16]:
y_pred=model.predict(X_test)

In [17]:
y_pred.shape

(300,)

In [18]:
y_pred

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1])

In [19]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,r2_score

In [20]:
confusion_matrix(y_pred,y_test)

array([[156,   3],
       [  1, 140]])

In [21]:
accuracy_score(y_pred,y_test)

0.9866666666666667

In [22]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       159
           1       0.98      0.99      0.99       141

    accuracy                           0.99       300
   macro avg       0.99      0.99      0.99       300
weighted avg       0.99      0.99      0.99       300



In [23]:
r2_score(y_pred,y_test)

0.9464739729693563

In [24]:
from sklearn.model_selection import GridSearchCV

In [ ]:
parameters={'criterion':['gini','entropy'],'max_depth':[2,3,4,5,6,7,8,9,10,11,12,15,20,30,40,50,70,90,120,150]}
gridsearch=GridSearchCV(DecisionTreeClassifier(),parameters)
gridsearch.fit(X_train,y_train)

In [ ]:
gridsearch.best_params_

In [ ]:
gridsearch.best_score_

In [ ]:
gridsearch.best_estimator_

In [ ]:
gridsearch.best_index_

In [33]:
y_pred_grid=gridsearch.predict(X_test)

In [ ]:
confusion_matrix(y_test,y_pred_grid)

In [ ]:
print(classification_report(y_test,y_pred_grid))

In [36]:
#https://www.youtube.com/watch?v=w4frwjt8uCo

P4.b
**2. Random Forest Classification with Artificial Generated Dataset**



In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [39]:
from sklearn.datasets import make_classification

In [40]:
X,y=make_classification(n_samples=1000,n_features=5,n_clusters_per_class=1,n_classes=2,random_state=2529)

In [41]:
X[0:5]

array([[ 1.54701705,  0.84770596, -0.41725021, -0.62356778, -0.19388577],
       [ 0.80633556,  0.40985594, -0.45641095, -0.3052022 ,  0.50935923],
       [ 0.94390268,  0.70041038,  1.11385452, -0.49394417,  1.42305455],
       [ 1.92091517,  0.95815739, -1.2235022 , -0.71578154,  0.66588981],
       [ 1.45270369,  0.69035375, -1.18119669, -0.52009219, -0.22745417]])

In [42]:
y[0:5]

array([0, 0, 1, 0, 0])

In [43]:
X.shape,y.shape

((1000, 5), (1000,))

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=2529)

In [46]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((700, 5), (300, 5), (700,), (300,))

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
model=RandomForestClassifier()

In [49]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [50]:
y_pred=model.predict(X_test)

In [52]:
y_pred.shape

(300,)

In [53]:
y_pred

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1])

In [54]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [55]:
accuracy_score(y_test,y_pred)

0.99

In [56]:
confusion_matrix(y_test,y_pred)

array([[156,   1],
       [  2, 141]])

In [57]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       157
           1       0.99      0.99      0.99       143

    accuracy                           0.99       300
   macro avg       0.99      0.99      0.99       300
weighted avg       0.99      0.99      0.99       300



In [59]:
from sklearn.model_selection import GridSearchCV
parameters={'n_estimators':[10,20,30,100,200,500],'max_features':['auto','sqrt'],'min_samples_split':[4,8],'bootstrap':[True,False]}
gridsearch=GridSearchCV(RandomForestClassifier(),parameters)
gridsearch.fit(X_train,y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'bootstrap': [True, False],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_split': [4, 8],
                         'n_estimators': [10, 20, 30, 100, 200, 500]})

In [60]:
gridsearch.best_params_

{'bootstrap': False,
 'max_features': 'auto',
 'min_samples_split': 8,
 'n_estimators': 200}

In [61]:
gridsearch.best_estimator_

RandomForestClassifier(bootstrap=False, min_samples_split=8, n_estimators=200)

In [62]:
gridsearch.best_index_

34

In [63]:
y_pred_grid=gridsearch.predict(X_test)

In [64]:
confusion_matrix(y_test,y_pred_grid)

array([[156,   1],
       [  2, 141]])

In [65]:
print(classification_report(y_test,y_pred_grid))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       157
           1       0.99      0.99      0.99       143

    accuracy                           0.99       300
   macro avg       0.99      0.99      0.99       300
weighted avg       0.99      0.99      0.99       300



In [66]:
print(classification_report(y_pred,y_pred_grid))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       158
           1       1.00      1.00      1.00       142

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300

